### ISSUE TITLE
Object IntPtr constructor

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#101]
From what I recall, the `this(Native.@new)` pattern breaks when subclassing, as we need to be going through either `Object()` or `Object(ConstructParameter[])` for the type integration code to run. The `IntPtr` constructor would simply wrap the `GtkApplication` as a foreign-created object.

_Originally posted by @firox263 in https://github.com/gircore/gir.core/pull/95#issuecomment-721092907_

Are you sure about this? Can't we just add the type dictionary integration to the Object(IntPtr) constructor, too?

**Comment by firox263** [comment]
I don't think I worded that very well, my bad.

We effectively have two constructors for GObject:
 * `Object(params ConstructParameter[])`: Used to create a _new object_, optionally with some construct-time properties set. The default constructor `Object()` is this constructor with no arguments provided.
 * `Object(IntPtr)`: Used to create a new wrapper to an _existing object_ somewhere in C.

With `Object(ConstructParameter[])`, object creation happens in the constructor, where we instantiate either a wrapper or a subclass depending on the object's reflected type. Whereas `Object(IntPtr)` shouldn't create an object, as the object we are wrapping already exists. When we create an object using `this(Native.@new)`, GLib creates an object for us first, then we wrap this existing object in a wrapper class. This causes all subclasses of `Gtk.Application` to be represented as a wrapper for `Gtk.Application`.

This split in constructors was by design in #52, so we aren't able to add type integration to both (and arguably wouldn't want to).

**Comment by badcel** [comment]
Thank you for clarifying this (again). You are right in case of subclassing this would not work. So this is obsolete. I try to remember it this time 😃 .
