### ISSUE TITLE
Verify if we should respect the "introspectable" attribute

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#487]
There are methods which are not introspectable e.g. g_param_spec_unref

Clarify if there are other ways to work around those methods.

**Comment by mjakeman** [comment]
We should respect this. In GTK 4, the `GtkPrinter` class has a property called "backend" which is non-introspectable:

```xml
<property name="backend" introspectable="0" writable="1" construct-only="1" transfer-ownership="none">
	<attribute name="org.gtk.Property.get" value="gtk_printer_get_backend"/>
	<doc xml:space="preserve" filename="../gtk/gtkprinter.c" line="128">The backend for the printer.</doc>
	<type/>
</property>
```

There's no way to generate this since `type` is empty. Respecting `introspectable` is probably the most sensible way of handling this at scale, since it puts the responsibility on the library rather than us for making sure all library features are accessible.

w.r.t. `g_param_spec_unref`, we should probably special case functions like that

**Comment by badcel** [comment]
We should not respect it in all cases. If the `introspectable` attribute is `false` it means that it is not compiled into the typelib file. As we are using the GIR files directly we are not forced to respect it.

Respecting it in all cases would also lead to a loss of functionality as we are already using some methods as part of our framework which are declared as not introspectable.

We have to solve each problem one by one. E.g. if a property provides no type, the generator should probably get more fault tolerant so the generation of a class does not fail if a property has no type.
