### ISSUE TITLE
Typedict expensive lookup

### ISSUE THREAD

**Issue by badcel** [gircore/gir.core#66]
A thought:

We should probably check if the GType of generic type 'T' is equal to the gtype from the pointer. That way, we can avoid the expensive lookup in the type dictionary for cases where we know the type we want (e.g. `Dialog.GetContentArea`).

_Originally posted by @firox263 in https://github.com/gircore/gir.core/pull/65#issuecomment-683268065_

-------

I created an issue so we don't forget about this comment. I currently don't see the expensive lookup. Perhaps you could just create a pull request?

**Comment by firox263** [comment]
Effectively, we'd retrieve the GType for the generic <T> and compare it with our known GType, adding it to the type dictionary in the process. That way if <T> is the true type of our ptr, we avoid an expensive type dictionary lookup, and if it isn't, we still register it in the type dict for future use.

For this we'll need a way of comparing GTypes (implementing `Equals()` and overriding `==/!=`), but I can't do it cleanly with our current implementation of GObject.Type (which wraps `Sys.Type`). I think this ties into the point @na2axl brought up about how we have `Sys.Type`/`Sys.Value`/etc in `Wrapper` instead of `Core`. If it's possible, I think we should move the contents of `Wrapper/API` into the core part and put the struct definitions in `.Abi.cs` partial classes like with `Object.Abi.cs`.

This would also have the benefit of keeping all library logic in `Core` and all wrapper functions in `Wrapper`.
