### ISSUE TITLE
Verify handling of out and inout array parameters

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#763]
This is a future TODO since `out` and `inout` array parameters are currently skipped for public bindings, at least for primitive and string values, but I also saw an issue with the internal bindings and wanted to record my findings for future reference

The internal bindings for functions such as `g_input_stream_read()` are incorrect and result in a crash, which I also reproduced with a simple C test library
- For an `out` parameter with `caller-allocates=true` the `ref byte[]` should actually just be `byte[]` since arrays are already a reference type. This could explicitly be `[Out] byte[]` [to be safe](https://stackoverflow.com/a/14366422) in case the native function doesn't get a direct pointer to the managed array.
- Similarly an `inout` parameter would be `[In, Out] byte[]`, not `ref byte[]`
- `out` parameters with `caller-allocates=false` (if they exist) would require investigation and possibly custom marshalling to deal with the memory allocation.

**Comment by badcel** [comment]
Consider using span / memory?

**Comment by cameronwhite** [comment]
I think Span would make sense for `caller-allocates=true` since then a stack-allocated buffer could be passed in.
Not sure if there are any cases of `caller-allocates=false`, but in that case the native function is probably doing the allocation and passing a pointer back so Span probably doesn't make sense there

**Comment by badcel** [comment]
@cameronwhite I think I would generate the internal API with `caller allocates true` similar to my HidApi implementation: [Sample](https://github.com/badcel/HidApi.Net/blob/9fb1bac6a07b14556151d482b90a3ace49fd0580/src/HidApi.Net/Internal/NativeMethods.cs#L42)

In HidApi I use a `ref byte` instead of `byte[]` as it is easy to get the reference to the first byte from a span. creating a byte array from a span would probably copy the data.

**Comment by cameronwhite** [comment]
👍 that sounds like the right approach to me for the internal API
