### ISSUE TITLE
Missing bindings for GLib.Variant

### ISSUE THREAD

**Issue by cameronwhite** [gircore/gir.core#843]
A full sweep is probably needed to make sure there are bindings for all the variant types, but the ones I found porting Pinta were:

- bool types: need `Variant.Create(bool)` and `bool GetBool()`
- more predefined `VariantType` constants would be convenient, currently only `"s"` and `"v"` have named constants
- dictionary types: the `"a{sv}"` variant type mapping strings to variants. It's only possible currently to construct an empty one via `Variant.CreateEmptyDictionary()`

**Comment by badcel** [comment]
@cameronwhite: I wonder if there should be more `VariantType` constants or if they should be removed altogether as those are only convenience. If the API is getting generated a user can create every type he wants to via a string. E.g.: `VariantType.New("i");`

**Comment by cameronwhite** [comment]
I think at least some sort of constant is useful so that it's more discoverable - otherwise you have to look up the GTK docs to find the right string to use and might make a typo

**Comment by badcel** [comment]
With constant you mean a string constant?

So you write: `VariantType.New(VariantType.String`?

We could have a static method instead:
`VariantType.GetString()`

Or a static property:
`VariantType.String`

I think I would avoid caching a lot of instances.

What do you think of implementing a custom [equality](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type) so that two `VariantTypes` are equal if they represent the same type (e.g. via [type_equal](https://docs.gtk.org/glib/method.VariantType.equal.html)?

**Comment by cameronwhite** [comment]
I think a separate build class is probably fine too, that also makes it more clearly separated as a convenience on top of the actual GTK API
