### ISSUE TITLE
Gst.Message src and other conventions

### ISSUE THREAD

**Issue by jnoyola** [gircore/gir.core#966]
I'm relatively new to GirCore, and I'm trying to find out how to access a `Gst.Message` source so that I can get a video overlay and set the window handle, even when using `autovideosink` where the source isn't known in advance. (This approach is described in the [gstreamer docs](https://gstreamer.freedesktop.org/documentation/video/gstvideooverlay.html?gi-language=c#two-basic-usage-scenarios).)

I was expecting to do something like this, except there's no `src` member.
```cs
pipeline.GetBus().SetSyncHandler((bus, msg) =>
{
    if (GstVideo.Functions.IsVideoOverlayPrepareWindowHandleMessage(msg))
    {
        var videoOverlay = new GstVideo.VideoOverlayHelper(msg.src.Handle, false);
        videoOverlay.SetWindowHandle(hwnd);
        videoOverlay.SetRenderRectangle(0, 0, 40, 40);
        videoOverlay.Expose();
        return BusSyncReply.Drop;
    }
    return BusSyncReply.Pass;
});
```

And on a related note, I'm wondering if anyone has tips for general usage and conventions for GirCore.Gst and GstVideo. For example, figuring out how to use the `VideoOverlayHelper` (which I having working with a raw `glimagesink` handle, just not the `autovideosink`/`SetSyncHandler` format above) took quite a bit of experimentation. Does this follow the pattern of any other lib or documentation out there, can I find it in the GirCore code, or is it being generated from somewhere? Or is there any intuition for which fields/functions I can find as class members, which might exist on a helper like this, or what might exist under `Functions`? Thanks in advance!

**Comment by badcel** [comment]
Hi, thanks for your report.

Unfortunately I can't really help with GStreamer as I'm not familar at all with those APIs. In general there are some things which I can state:

- It is very well possible that GStreamer has some fundamental issues as it is it's own "System" with needs special implementation details (see #784). This has not happened yet and is not on the immediate planing list.
-  The API is generated from gir files and thus correlates to the [C API](https://gstreamer.freedesktop.org/documentation/libs.html?gi-language=c) in a certain way. But it is possible that not all elements are available due to missing stuff in the generator. The current [GirCore Gst API](https://gircore.github.io/api/Gst.html) is available on the website. Which functions are available as functions is defined in the gir files. The official API probably should correlate to the gir file. If a function in the official api does not have an instance parameter it will probably be a global function which is not part of any class.

**Comment by jnoyola** [comment]
Thanks for the pointers! I got this working with internals plus a custom binding. I had issues using the generated `Gst.Internal.MessageData`, both because of the overlapping field offsets in `MutexData`, and because of the delegates in `MiniObjectData`. For my purposes, I just defined the following:

```cs
[StructLayout(LayoutKind.Explicit)]
public struct MessageData
{
    [FieldOffset(64)]
    public Gst.MessageType Type;
    [FieldOffset(72)]
    public ulong Timestamp;
    [FieldOffset(80)]
    public IntPtr Src;
    [FieldOffset(88)]
    public uint Seqnum;
}
```

And then I could embed the overlay like this.

**Question:** Does this look correct with the usage of `DangerousGetHandle` and VideoOverlayHelper `ownedRef=true`?

```cs
Gst.Module.Initialize();
GstVideo.Module.Initialize();
Gst.Application.Init();
Gst.Element pipeline = Gst.Functions.ParseLaunch("souphttpsrc location=https://gstreamer.freedesktop.org/data/media/sintel_trailer-480p.webm ! decodebin ! videoconvert ! autovideosink");

nuint hwnd = (nuint)((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;
pipeline.GetBus().SetSyncHandler((bus, msg) =>
{
    if (GstVideo.Functions.IsVideoOverlayPrepareWindowHandleMessage(msg))
    {
        var data = Marshal.PtrToStructure<MessageData>(msg.Handle.DangerousGetHandle());
        var videoOverlay = new GstVideo.VideoOverlayHelper(data.Src, true);
        videoOverlay.SetWindowHandle(hwnd);
        var setRect = videoOverlay.SetRenderRectangle(0, 0, 640, 360);
        videoOverlay.Expose();
        return BusSyncReply.Drop;
    }
    return BusSyncReply.Pass;
});

pipeline.SetState(State.Playing);
```

![image](https://github.com/gircore/gir.core/assets/4064932/6f2be74f-d8ce-4810-b0ac-c540ecd79ac3)

Only tested on Windows so far. I see that autovideosink resolves to `d3d11videosink` for me, which is able to embed in the MAUI window. However `glimagesink` and `d3dvideosink` were able to embed in other windows (notepad, powershell) but not the MAUI window, so I'm guessing maybe there's a restriction based on which directx version is being used or something.

**Comment by badcel** [comment]
Hi thanks for pointing your solution out. Someone needs to take a look at why the struct is generated in the wrong way.

It would be super nice if you could open a new issue including all your infos with what is wrong with this struct to be able to fix the generator.

Then we could fix all your other questions here and the struct issue is handled else where. (Perhaps link into this issue to have the reference)

Now to your questions:
- [VideoverlayHelper](https://gircore.github.io/api/GstVideo.VideoOverlayHelper.html#GstVideo_VideoOverlayHelper__ctor_System_IntPtr_System_Boolean_) is an interface. The second parameter states if the instance is already owned by GirCore. If not GirCore needs to acquire a reference on the instance. The message itself [owns the source](https://github.com/Xilinx/gstreamer/blob/ec5e781e6bf2b77ad632068a42d8eaa53a2950ba/gst/gstmessage.c#L272). So you need to pass `false` as second parameter. Otherwise GirCore would effectively steal the instance as the message and GirCore would want to free the same reference which would result in a double free bug.
- Additionally I read in the docs that you [should unref the message in the sync handler if your return drop](https://gstreamer.freedesktop.org/documentation/gstreamer/gstbus.html?gi-language=c#GstBusSyncHandler). I don't know why this can't happen automatically by GST but if the documentation states it, it is probably the right thing to do. GirCore tries hard to get references which are owned by itself so the data is kept around as long as the c# object is alive. If only the c# instance is released this will probably not free the message itself as some Gst code has another reference to it. So I would interpret the docs like a call to manually release the instance owned by Gst. In doubt this would be a question for the gst developers.
